### ISSUE TITLE
Y-Stop mount missing switch mounting holes

### ISSUE THREAD

**Issue by mobilemcclintic** [VzBoT3D/VzBoT-Vz330#1]
Y-Stop mount is missing the holes to mount the switch.  It's not easy to see in the full step file because the screws are there.  If you hide them, the mounting surface is solid.

**Comment by simonvez** [comment]
Thanks for reporting will fix that in CU4

**Comment by simonvez** [comment]
new STL have been uploaded and CAD has been fixed for CU4 release
