### ISSUE TITLE
printed motor mounts

### ISSUE THREAD

**Issue by LonyB** [VzBoT3D/VzBoT-Vz330#10]
Printed motor mounts 3D top images do not fit bottoms, holes do not line up. No hole where there should be one. Images do not match causing confusion. Appears to be an Older .stl

**Comment by chrishenze** [comment]
I rechecked the STL models and couldn't find what you are meaning. Could you upload a screenshot?

**Comment by LonyB** [comment]
Looks like I have it figured out, I downloaded one set of .stl files for the bottom then the tops later after the revisions so thats why they didn't match up. but stl doesn't match the 3d view in the folder or at least that's how it was earlier today.
