### ISSUE TITLE
Wiki - Motors (Stepper)

### ISSUE THREAD

**Issue by FLXMM** [VzBoT3D/VzBoT-Vz330#13]
Didnt know where to mention this. Hope hear is right.

The mentioned data in the Motors table for the E3D High Torque Nema17 is wrong. And the Units for Inductance and Ampere are switched!

https://e3d-online.zendesk.com/hc/en-us/article_attachments/360016686858/High_Torque_Motor.pdf

E3D High Torque 
Inductance : 2.8mH (instead of 2.8A)
Ampere : 1.68A (instead of 2.8mH)

**Comment by simonvez** [comment]
corrected thanks !
