### ISSUE TITLE
about pei？

### ISSUE THREAD

**Issue by psusong** [VzBoT3D/VzBoT-Vz330#14]
Hello, can you see how you dealt with the pei, whether it is the magnet placed behind the aluminum plate or the magnetic surface directly attached

![O1CN01k1jqea1Vrqs3z8ouq_!!3430562707-0-cib (1)](https://user-images.githubusercontent.com/9137231/149799287-860fd1c4-dfef-40de-9896-47a196fbdd12.jpg)

**Comment by chrishenze** [comment]
The magnetic sheet should be directly put on the heated bed.

**Comment by psusong** [comment]
![O1CN01iOxXHP1X7i7YJf6Go_!!411112877](https://user-images.githubusercontent.com/9137231/150123912-5488e98b-492f-40b1-91b7-6071d50a8a2d.jpg)
I see that some people do this. I don't know if it will be deformed. If the magnetic film is directly attached, will it be uneven?

**Comment by chrishenze** [comment]
You don't need a magnetic sheet if you already have magnets in your bed. You would just put the spring steel plate with the PEI layer on it.
