### ISSUE TITLE
The back plate with no tensioner.stl is not suitable for new EVA 2.4.2 models

### ISSUE THREAD

**Issue by arieslight** [VzBoT3D/VzBoT-Vz330#17]
![IMG_20220124_105300R](https://user-images.githubusercontent.com/12478607/150714559-8fbae20a-1057-48ab-accd-023f28ef05bb.jpg)
![IMG_20220124_105237R](https://user-images.githubusercontent.com/12478607/150714564-1104d758-1db9-4bd5-bca4-7d654c017706.jpg)

**Comment by carloshespanhol** [comment]
I am planing to use this part and have the same problem

**Comment by simonvez** [comment]
we will provide one . There is already one if you look in the pull request. A member has made one. We will review it and publish it if it is good

**Comment by carloshespanhol** [comment]
In the pull request I found one with tensioner, I' m looking for the back without tensioner.

**Comment by arieslight** [comment]
yeah, In the pull request there is no one without tensioner. I modified one without tensioner but it's not perfect

**Comment by arieslight** [comment]
![IMG_20220125_232803R](https://user-images.githubusercontent.com/12478607/151008097-1f9f902e-7282-420d-866b-f9b33e5695a8.jpg)
![IMG_20220125_232636R](https://user-images.githubusercontent.com/12478607/151008129-ddbb3dbb-aeb2-4676-8047-4f615f9a19d3.jpg)
![IMG_20220125_232755R](https://user-images.githubusercontent.com/12478607/151008165-e8a050ae-ff62-4c8d-815f-ad896e3fd7f1.jpg)

**Comment by arieslight** [comment]
[plate with no tensioner（beta by arieslight）.zip](https://github.com/VzBoT3D/VzBoT-Vz330/files/7934921/plate.with.no.tensioner.beta.by.arieslight.zip)
it is not perfect,but If you can't wait for the official release，you can try it

**Comment by carloshespanhol** [comment]
Thank you

**Comment by carloshespanhol** [comment]
arieslight could you post the step file I want to make some changes in the belt fixing holes
