### ISSUE TITLE
BOM for the aluminum front idler

### ISSUE THREAD

**Issue by mouamart** [VzBoT3D/VzBoT-Vz330#19]
there is no BOM for the aluminum front idler. just ordered my kit from mellow I hope I can get the BOM for the aluminum front idler before they arrive. thanks and a Tim Hortense coffee on the way to u ;)

**Comment by simonvez** [comment]
I will update the BOM now

**Comment by simonvez** [comment]
https://github.com/VzBoT3D/VzBoT-Vz330/tree/master/Assemblies%20BOM%20and%20STL/Gantry/Front%20Idler%20mounts/Aluminum/BOM
