### ISSUE TITLE
BOM for single Z motor mount is missing 4 screws

### ISSUE THREAD

**Issue by Polar-Ted** [VzBoT3D/VzBoT-Vz330#20]
https://github.com/VzBoT3D/VzBoT-Vz330/tree/master/Assemblies%20BOM%20and%20STL/Z%20assembly/Single%20Motor%20Mount/BOM

The 4 M3x10mm screws to mount the motor are missing from the BOM for the mount.

**Comment by simonvez** [comment]
thanks ! I will add them
