### ISSUE TITLE
Vz-HextrudrORT - STLs vs CAD

### ISSUE THREAD

**Issue by FLXMM** [VzBoT3D/VzBoT-Vz330#21]
Hi the BOM and STLs differ from the 
https://github.com/VzBoT3D/VzBoT-Vz330/blob/master/CAD/Vz-HextrudORT/Vz-Hextrudort-Low%20motor.step 
there is an additional screw on the bottom right of the main body and the backplate in the CAD file but not in the STLs

**Comment by simonvez** [comment]
Yes I added another screw to stiffen the body assembly. I will update the BOM. Thanks for spotting it
