### ISSUE TITLE
klicky probe？

### ISSUE THREAD

**Issue by psusong** [VzBoT3D/VzBoT-Vz330#22]
Can add support for klicky probe? Works great on Voron.
thank

**Comment by psusong** [comment]
https://github.com/jlas1/Klicky-Probe

**Comment by simonvez** [comment]
Hi, are you requesting the support for the EVA or the Vz-Printhead ?

**Comment by psusong** [comment]
My machine has not been installed, and when it is installed, I will study

**Comment by hschraep** [comment]
i would preffer it for both heads.

**Comment by psusong** [comment]
[SSerpenteSS](https://github.com/SSerpenteSS) Make a fork of vzbot

https://github.com/jlas1/Klicky-Probe/pull/69

**Comment by jlas1** [comment]
Done, published
