### ISSUE TITLE
VZ Eva Bltouch Dragon support?

### ISSUE THREAD

**Issue by sn0wfl4key** [VzBoT3D/VzBoT-Vz330#23]
There seems to be no support for the VZ Eva 2.4 for a bltouch, on the original it had some mounting holes in hte front face.
Is there something i have missed?

**Comment by simonvez** [comment]
did you check the community mods ? im sure there are one

**Comment by simonvez** [comment]
I highly suggest you upgrade to the Vz-Printhead. We dont develop arround Eva anymore
