### ISSUE TITLE
Motor mounts inside the housing

### ISSUE THREAD

**Issue by ckvsoft** [VzBoT3D/VzBoT-Vz330#24]
Hi
I have a question about the x/y motors.
Have you ever had heat problems with the motors in the closed housing? It could be very warm inside.
Would it be better to place the motors outside?

lg Chris

**Comment by mouamart** [comment]
I believe there is a printed part option to mount your motor outside the enclosure,

**Comment by ckvsoft** [comment]
Yes there are. I wanted to know if there were heat problems with long prints when the motors are inside the housing. Or are LDO motors advisable here in any case?

**Comment by ckvsoft** [comment]
I like the concept very much. But I'm not sure if I should buy a Tronxy and have a lot of unneeded parts or if I should just get the profiles for the frame. If I then compare the price, a whole Tronxy is not really more expensive than if I only get the frame material ;)
