### ISSUE TITLE
Missing Lm12uu mount stl file?

### ISSUE THREAD

**Issue by quocanhcgd** [VzBoT3D/VzBoT-Vz330#26]
In Bed assem, i can't find print part for LM12UU, but in Z up and down have it. 
Is that missing or can't use Lm12uu?

**Comment by simonvez** [comment]
https://github.com/VzBoT3D/VzBoT-Vz330/blob/master/Assemblies%20BOM%20and%20STL/Bed%20Assembly/STLs/lmu12luu_Mount.stl.stl

**Comment by simonvez** [comment]
thats what you need ? sorry for the long reply
