### ISSUE TITLE
Link to cpap fan broken for USA

### ISSUE THREAD

**Issue by kdb424** [VzBoT3D/VzBoT-Vz330#27]
The aliexpress link to the fan is not working with the message "This item cannot be shipped to United States". Any chance there is an alternative link for a seller that ships to the US?

**Comment by simonvez** [comment]
there are 2 links in the bom.. are both of them not working for US ?

**Comment by simonvez** [comment]
![image](https://user-images.githubusercontent.com/37383368/172412296-a1de41d7-5830-4b87-9a05-5306737d469e.png)

the first link works : <html>
<body>


https://s.click.aliexpress.com/e/_AEsHxz
--



</body>
</html>
