### ISSUE TITLE
Theme contrast

### ISSUE THREAD

**Issue by alfrix** [VzBoT3D/VzBoT-Vz330#28]
i saw that you were struggling to see the text on your theme, so i made some mods to your theme
 
Toned down background so it contrast more
Optional background without logo
Option to use the v logo instead of klipper
Tweak style.css to have a black border around text (needed for the busy background)

You can use whatever combination you want, or none of them.

[theme-tweaks.zip](https://github.com/VzBoT3D/VzBoT-Vz330/files/8336754/theme-tweaks.zip)

**Comment by simonvez** [comment]
thanks kind sir..I will give it a try
