### ISSUE TITLE
FAN DUCT CAD WRONG

### ISSUE THREAD

**Issue by lipk888** [VzBoT3D/VzBoT-Vz330#29]
HI TEAM:
i just found issue about FAN duct, which show center hold not pass through.
can you help update CAD

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/59854686/160426584-264f40f0-9f2c-4c85-9f9d-8d85c31e926b.png">

**Comment by simonvez** [comment]
sorry for the late reply. I have loaded the CAD for the Vz-Printhead. I downloaded the step file from github to be sure and loaded and it is corrected for me. Maybe you got the early release. But the cad is fine now. you can download it
thanks
Vez
