### ISSUE TITLE
Z stop that hands off bed

### ISSUE THREAD

**Issue by coilboii** [VzBoT3D/VzBoT-Vz330#3]
Is there a stl for the hindge that hangs off the side of the bed with the screw sticking up to hit the z stop or is there a item you used. Nothing in the bom nor the stl

**Comment by coilboii** [comment]
Supposed to say hangs off

**Comment by simonvez** [comment]
here mate : https://github.com/VzBoT3D/VzBoT/blob/master/Assemblies%20BOM%20and%20STL/Bed%20Assembly/STLs/Z%20height%20adjustement%20screw%20mount.stl

**Comment by simonvez** [comment]
if you want to test the new one coming in CU4... I can share you the files now ?

**Comment by simonvez** [comment]
[Z switch mount.zip](https://github.com/VzBoT3D/VzBoT/files/7824916/Z.switch.mount.zip)

here you can test it. It will now mount on the right side indead, to avoir interfering with the Y stop switch. This is a cleaner look as well.

**Comment by simonvez** [comment]
![image](https://user-images.githubusercontent.com/37383368/148457114-8a94c10c-abfa-4b3c-9d93-11c48a1ec73b.png)
