### ISSUE TITLE
missing the fan base

### ISSUE THREAD

**Issue by psusong** [VzBoT3D/VzBoT-Vz330#30]
![QQ图片20220330220846](https://user-images.githubusercontent.com/9137231/160855063-26821b68-02f8-4ff8-8ccf-f76c81cfed26.png)
Hi, where can I find the printed drawings of this fan base

**Comment by psusong** [comment]
i find https://www.thingiverse.com/thing:5252555

**Comment by psusong** [comment]
Is there a version of 4010fan?

**Comment by simonvez** [comment]
no.. only the small fan to save weight
