### ISSUE TITLE
BOM no download link

### ISSUE THREAD

**Issue by W141-ID** [VzBoT3D/VzBoT-Vz330#33]
I can't download the BOM anymore. Need it for comparison and editing.

**Comment by simonvez** [comment]
I Waym99.. not sure anything changed on our side. If you cant access the bom anymore, what error message you get? If you can access it and want to have a local copy, you could simply copy paste all the content to a local spreadsheet :)

**Comment by W141-ID** [comment]
I can actually access it but not in the same way as the 235. It's somewhat restricted. I read some where you have to make it public.

Awesome project. Thank you for your effort!

**Comment by Roberto-Hernandez-Jr** [comment]
Hello also having this issue, wanted to download to make custom 510 one

**Comment by simonvez** [comment]
please try now

**Comment by Roberto-Hernandez-Jr** [comment]
> please try now

Works now! Thank you
