### ISSUE TITLE
Sherpa Mini mount bad geometry

### ISSUE THREAD

**Issue by Arakon** [VzBoT3D/VzBoT-Vz330#36]
The sherpa mini (misspelled "nini") STL [here](https://github.com/VzBoT3D/VzBoT-Vz330/blob/master/Assemblies%20BOM%20and%20STL/PrintHeads/EVA-Vz/STLs/Top-MGN9-Sherpa%20nini.stl) has a bulge in four areas that is blocking the internal hole where a long bolt has to pass through.
This can be fixed by drilling, but it doesn't seem like this is intentional.
![sherpa](https://user-images.githubusercontent.com/12016360/174458615-d76bf308-7133-4760-b3b1-86e0bcc610f7.png)

**Comment by simonvez** [comment]
thanks for reporting, and sorry for the late response. I don't have that cad unfortunately, but  will try to find who made it so we can fix it.
