### ISSUE TITLE
Hextrudort high motor mount feed gear problems

### ISSUE THREAD

**Issue by FloxRoxX** [VzBoT3D/VzBoT-Vz330#38]
Hi, i printed the HextrudOrt with the high motor mount (not the helical version). Additionally i use the original Bondtech gears and noticed, that the gears do not make good contact with the filament.

Hextrudort was printed on ABS like resin for high temp resistances on my elegoo mars. So accuracy cannot be the problem ;)

See picture, you can clearly see that the filament is only touching the left screw barely. Also with tensioning the gears fully up the tension isnt enought... Any help is appreaciated :)

![IMG_20220712_000430](https://user-images.githubusercontent.com/1994104/178368336-e54e3b72-fdf9-49a3-ba1e-3908092468cb.jpg)

EDIT:
Here a little video that shows the problem in action...

https://photos.app.goo.gl/UMnWPYBEVg9GL4wj9

**Comment by simonvez** [comment]
there was a new model published that has an extra bolt at the bottom to help. But looking at your video it looks like the printed parts are not stiff enough maybe? Try with the new model it should help a lot
