### ISSUE TITLE
Source (f3d/step) files missing for dual motor mount

### ISSUE THREAD

**Issue by tonyshackelton** [VzBoT3D/VzBoT-Vz330#40]
Hi, I am trying to combine parts from the 535 rod mounts and dual motor mounts into a singular part for those that wish to modify the tronxy bed for VZBot use/enclosure. I am unable to locate the cad files, and have reached out via discord. I wanted to make an issue here, in case an admin does have these files, or if not, they could be merged into the repo once procured.

**Comment by simonvez** [comment]
cad file can be found here: https://github.com/VzBoT3D/VzBoT-Vz330/tree/master/CAD/Z%20assembly/Dual%20Z%20motor%20mount
