### ISSUE TITLE
[Vz330] Front Door Hinge Part 2 has 4.2mm holes to mount panel, but panel has 3.2mm holes

### ISSUE THREAD

**Issue by Arakon** [VzBoT3D/VzBoT-Vz330#42]
BOM specifies 4mm bolts, too.
![image](https://user-images.githubusercontent.com/12016360/188060010-5ff67c63-d165-41fe-be73-eeda2e36fa97.png)

![image](https://user-images.githubusercontent.com/12016360/188060025-5e375fe0-58a6-4f3c-b813-8922034dfd1e.png)

I helped it using thin nylon washers, which just so happened to have the size of an M4 screw head.

Please either adjust the hole diameter in the enclosure step files or STL, and adjust the BOM.

Also, the build manual specifies M4x40 bolts to connect the two hinge halves, but that's too short, M4x50 is required at least.

**Comment by simonvez** [comment]
Hi there, thanks for reporting this. sorry for the late reply. The front door holes were corrected a while ago. Its using M4 so the holes were changed to 4.3mm. Thanks
