### ISSUE TITLE
New Release Rar Extracting Error

### ISSUE THREAD

**Issue by chmfhm** [VzBoT3D/VzBoT-Vz330#46]
Download 2 3 times but always got error while extracting rar file or tar.gz file

**Comment by simonvez** [comment]
its a zip file. Windows zip file. It was updated on Jan 2nd. Can you try again ?

**Comment by Billy-d-Kidd** [comment]
Can you clone the repository?

**Comment by simonvez** [comment]
This was fixed a while ago
