### ISSUE TITLE
AWD trouble at slow speed 

### ISSUE THREAD

**Issue by trackhacs** [VzBoT3D/VzBoT-Vz330#49]
I have AWD configuration with TMC5160. It works beautiful for normal printing, without any problems.

However, at (very) low speeds  and low acceleration, e.g. during klipper tuning_tower test with suggested acceleration of only 500,  one of the TMC is reporting "no load" and klipper chickens out. 

Guess this is due to both motor pulling in same direction and that might cause one motor to see no load. 

any experience with this?

**Comment by simonvez** [comment]
I have personally never heard of that. Did you do the sync procedure ?

**Comment by trackhacs** [comment]
yes - but I did only loose one motor per belt. just saw your (?) video about it and will try to loosen all 4 motors.

**Comment by simonvez** [comment]
I do only 1 motor per belt too..but doing all 4 is better...just way harder
