### ISSUE TITLE
Fusion360 link is broken

### ISSUE THREAD

**Issue by spuder** [VzBoT3D/VzBoT-Vz330#5]
The link in the README does not load: https://a360.co/3nlDd2s
Not sure if this is a problem with the model, or autodesks problem. 
<img width="973" alt="Screen Shot 2021-12-21 at 1 06 40 AM" src="https://user-images.githubusercontent.com/242382/146893969-e02419d9-92df-461e-ad9b-48e47fbfc58d.png">

**Comment by simonvez** [comment]
know bug, everytime I update and save the Fusion file, I need to click on the URL so it reload it again. I will try to not foget this step for the next times. Thanks for reporting this
