### ISSUE TITLE
Different knob-cab for NEMA17 Left and Right Motor mount with Tensioner

### ISSUE THREAD

**Issue by EmanueleGiannuzzi** [VzBoT3D/VzBoT-Vz330#51]
These 2 STL contain different models:
LEFT MOTOR MOUNT: https://github.com/VzBoT3D/VzBoT-Vz330/blob/master/Assemblies%20BOM%20and%20STL/Gantry/Motor%20Mounts/Printed/Left%20Motor%20Mount%20Nema17%20with%20Tensioner/STLs/knob-cap.stl
RIGHT MOTOR MOUNT: https://github.com/VzBoT3D/VzBoT-Vz330/blob/master/Assemblies%20BOM%20and%20STL/Gantry/Motor%20Mounts/Printed/Right%20Motor%20Mount%20Nema17%20with%20Tensioner/STLs/knob-cap.stl

https://i.imgur.com/r04ShFW.png

They are 7mm and 9mm long. 
Looking at the CAD, the correct one should be the one in the Right Motor mount folder (7mm).

**Comment by simonvez** [comment]
Good catch ! thanks. I have updated it
