### ISSUE TITLE
webview does not load (printed version)

### ISSUE THREAD

**Issue by trackhacs** [VzBoT3D/VzBoT-Vz330#52]
the 3d web model of the printed version does not open. though the machined version does. 

https://myhub.autodesk360.com/ue2b28c05/g/shares/SH9285eQTcf875d3c53925206205b90b0187

**Comment by simonvez** [comment]
looking

**Comment by simonvez** [comment]
fixed ! I dont know why fusion has so much bug with this. but its fixed now
https://a360.co/3zy0yob

**Comment by trackhacs** [comment]
yep works !
