### ISSUE TITLE
Printed Y gantry bottom has thin layer in nut hole

### ISSUE THREAD

**Issue by random-eel** [VzBoT3D/VzBoT-Vz330#54]
Haven't printed this part yet (Y_gantry_bottom_left.stl), but I do believe the center of a hole that nut sits should be a thru hole, otherwise it would block the tip of M5x30mm bolt from going through.
Is this something that needs to be drilled out or is this how its supposed to be?

![image](https://github.com/VzBoT3D/VzBoT-Vz330/assets/4577638/3d0b2444-0edd-477b-9d6f-6ec9b204691c)
![image](https://github.com/VzBoT3D/VzBoT-Vz330/assets/4577638/81828e58-6529-4500-87b5-f8ea35f7b89a)

**Comment by jaarenhoevel** [comment]
I suppose that is on purpose to make it easier to print. That way the following round perimeters are not floating in the air.
You may want to print it with the flat side touching the build plate tho.

**Comment by simonvez** [comment]
Yes its to avoid printing support. Need to punch through or drill through
