### ISSUE TITLE
full printer step opening problem

### ISSUE THREAD

**Issue by Moreno-sky** [VzBoT3D/VzBoT-Vz330#55]
i have a problem during the opening of the step file of the full printer, my CAD software crash near the end of the opening

**Comment by magnificu** [comment]
I have the same problem.
32-bit software will crash due to memory overflow

**Comment by simonvez** [comment]
What software do you guys use?

**Comment by simonvez** [comment]
You can try the web version instead. The full cad is huge and you need quite a good pc to load it

**Comment by HumbleDeer** [comment]
One solution we can issue, is a CAD model with all step files placed in there separately.

Even better would be SLDPRT exports, as STEP files need to be "converted" from solid body definitions to solid bodies and given surfaces that are calculated at opening, before they're displayed.

**Comment by EduardoMDSousa** [comment]
Wy? My old laptop with intel grafics 4gb ran Open The full CAD on Fusion360.
