### ISSUE TITLE
Octopus Board

### ISSUE THREAD

**Issue by DeForestDiamond** [VzBoT3D/VzBoT-Vz330#57]
Hey!

In the BOM one if the options is the BTT Octopus but I can't find a config or bin file for it anywhere. Would you happen to have one kicking around? Preferably the config as I bought the "Max EZ" version and will probably have to change pins. 

I did try making one but I have nearly zero experience and I'm too afraid to try it lol.

Thanks!!!

**Comment by simonvez** [comment]
Im sure there are people that run this board. Might want to in discord or fb
