### ISSUE TITLE
Mellow 330 STL list suggested changes

### ISSUE THREAD

**Issue by 1980alexGS** [VzBoT3D/VzBoT-Vz330#62]
1. I think the items in https://github.com/VzBoT3D/VzBoT-Vz330/tree/master/Assemblies%20BOM%20and%20STL/enclosure/Front%20door%20latches/Magnetic%20latch
should replace the different door latch items in 'Mellow kit - all STLs' - Enclosure/Locking latch, since the kit now includes magnets.

2. The Back Electronic Bay section contains 'Front cover', 'Back cover', and 'screen mount frame' which I don't think belong there, because they appear in the Screen Mount section - please consider removing them from Back Electronic Bay.

3. Enclosure/Panel Trim - 'Trim - center x14' should be x16. Four in each side panel and eight in the top hat.

4. Vz-Printhead - 'Fan duct 2510-With flange for Vz-Printhead' - is it possible to increase hole sizes to 2.5mm, since the kit includes 4x M3x14mm screws which work for mounting the fan as long as the holes are drilled out to 2.5mm. I guess this is probably easier than changing the screws in the kit :)

5. - optionally - consider removing the 2020 Endcaps from the Frame section (they didn't fit for me and they seem unnecessary because the extrusion ends are coloured black), plus the Foot Spacer needs to be about 3.6mm thick to suit the rubber feet supplied in the kit (perhaps indicate this in the name of the file if it is difficult to change the size of the STL)

Thanks!

**Comment by EduardoMDSousa** [comment]
Hi the stl are genéric, for all options , kit, and self sorced frame etc , still the best , is download the full printer CAD, and export , since vez keep all parts updated 1st on cad .

**Comment by 1980alexGS** [comment]
Right, yes - I understand that STLs in other places can remain generic, i.e. both types of latches, different hole sizes, different display housings etc.

I think the Mellow 330 STL list.zip file should contain the STLs relevant to the Mellow 330 kit - and that specifically is what I’m trying to help with here. I’m happy that the driver fan holder was added after I mentioned it previously. 

Thanks

**Comment by simonvez** [comment]
thanks we will look at it

**Comment by simonvez** [comment]
all done
