### ISSUE TITLE
Electronic 

### ISSUE THREAD

**Issue by mouamart** [VzBoT3D/VzBoT-Vz330#7]
your using mellow super 8 motherboard as an official board for the build, raspberry pi 3, pitft50, 8 bar relays ext. Can you add wiring diagrams and instructions on how to wire everything together. Thanks in advance

**Comment by simonvez** [comment]
the 8bar relay is no longer used in my case since the Super8 has enough fan outputs for our needs.  The wiring is pretty straight forward for the rest.  The Pitft50 is wired with a 1m ribbon cable for pi

**Comment by mouamart** [comment]
> the 8bar relay is no longer used in my case since the Super8 has enough fan outputs for our needs. The wiring is pretty straight forward for the rest. The Pitft50 is wired with a 1m ribbon cable for pi

Then probably you should remove it from the bom as I did purchase it based on the bom list. 
I do understand it's straight forward and probably won't take me much to figure it out but a wiring diagram based on the BOM would b helpful for a lots of people as lots of people don't know how to wire a thing without instruction.

**Comment by simonvez** [comment]
yes I need to work on this too

**Comment by simonvez** [comment]
I will make the relay optional for those running smaller boards

**Comment by simonvez** [comment]
Thanks a ton Mouamart!!!
