### ISSUE TITLE
Google spreadsheet. 

### ISSUE THREAD

**Issue by shawnp30** [VzBoT3D/VzBoT-Vz330#8]
I’m trying to use the Google spreadsheet for the bom to make changes to the build size. Is there a way to open the Googlespread sheet in sheets on iPhone?

**Comment by simonvez** [comment]
I think you can get the suite installed no?

**Comment by chrishenze** [comment]
Here is the normal link to the spreadsheet, this shouldwork better?
https://docs.google.com/spreadsheets/d/1eNbgQ2HAe7iDxFRou1gHZOtjP1PLiPEpZYigivr-bK0/edit#gid=242794051

**Comment by tehmaze** [comment]
Works fine on iPhone with https://apps.apple.com/nl/app/google-sheets/id842849113

![image](https://user-images.githubusercontent.com/3327/148557383-04905737-3ef0-4630-84a1-bb1bb681406e.png)

**Comment by fabform** [comment]
Handy to locate google sheet id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
